ScreenManager:
    LoginScreen:
        name: "login"

    RegisterScreen:
        name: "register"

    DashboardScreen:
        name: "dashboard"

    RestaurantScreen:
        name: "restaurant"

    CartScreen:
        name: "cart"

    AddressScreen:
        name: "address"

    OrdersScreen:
        name: "orders"

    WalletScreen:
        name: "wallet"

    CardsScreen:
        name: "cards"

    ProfileScreen:
        name: "profile"

    ChefDashboardScreen:
        name: "chef_dashboard"

    ChefMenuScreen:
        name: "chef_menu"

    DeliveryDashboardScreen:
        name: "delivery_dashboard"

    DeliveryOrdersScreen:
        name: "delivery_orders"

    DeliveryActiveScreen:
        name: "delivery_active"

    DeliveryProfileScreen:
        name: "delivery_profile"
